export { default as HeroSection } from './HeroSection'
export { default as FeaturesSection } from './FeaturesSection'
export { default as EvidenceSection } from './EvidenceSection'
export { default as TestimonialsSection } from './TestimonialsSection'
export { default as PricingSection } from './PricingSection'
export { default as CTASection } from './CTASection'